/* eslint-disable no-undef */
export const API_URL = process.env.NEXT_PUBLIC_API_URL;
export const NEXT_PUBLIC_FIREBASE_API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY;
export const NEXT_PUBLIC_AUTH_DOMAIN = process.env.NEXT_PUBLIC_AUTH_DOMAIN;
export const NEXT_PUBLIC_PROJECT_ID = process.env.NEXT_PUBLIC_PROJECT_ID;
export const NEXT_PUBLIC_STORAGE_BUCKET = process.env.NEXT_PUBLIC_STORAGE_BUCKET;
export const NEXT_PUBLIC_MESSAGING_SENDER_ID = process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID;
export const NEXT_PUBLIC_MESSAGING_APP_ID = process.env.NEXT_PUBLIC_MESSAGING_APP_ID;
export const NEXT_PUBLIC_MESSAGING_MEASUREMENT_ID =
	process.env.NEXT_PUBLIC_MESSAGING_MEASUREMENT_ID;
export const NEXT_PUBLIC_WEBSITE_URL = process.env.NEXT_PUBLIC_WEBSITE_URL;
export const NEXT_PUBLIC_CLOUDINARY_API_KEY = process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY;
export const NEXT_PUBLIC_UPLOAD_PRESET = process.env.NEXT_PUBLIC_UPLOAD_PRESET;
export const NEXT_PUBLIC_CLOUDINARY_URL = process.env.NEXT_PUBLIC_CLOUDINARY_URL;
export const NEXT_PUBLIC_CLOUD_BUCKET = process.env.NEXT_PUBLIC_CLOUD_BUCKET;
export const NEXT_PUBLIC_NOTIFICATION_KEY = process.env.NEXT_PUBLIC_NOTIFICATION_KEY;
export const NEXT_PUBLIC_NOTIFICATION_SERVER_KEY = process.env.NEXT_PUBLIC_NOTIFICATION_SERVER_KEY;
export const NEXT_PUBLIC_GUMROAD_LINK = process.env.NEXT_PUBLIC_GUMROAD_LINK;
export const NEXT_PUBLIC_GUMROAD_ACCESS_TOKEN = process.env.NEXT_PUBLIC_GUMROAD_ACCESS_TOKEN;
export const FEEDBACK_FORM =
	"https://docs.google.com/forms/d/e/1FAIpQLSe9J-t927pS-dXPY_oDSiJmcJ8iuJSRq9esptc3UrJ244MJRg/viewform";
export const NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY;
export const NEXT_PUBLIC_STRIPE_SUBSCRIPTION_ID = process.env.NEXT_PUBLIC_STRIPE_SUBSCRIPTION_ID;
export const STRIPE_SECRET_KEY = process.env.NEXT_PUBLIC_STRIPE_SECRET_KEY;
